# Generated by Django 6.0.5 on 2026-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time', models.FloatField()),
                ('amount', models.FloatField()),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
                ('v9', models.FloatField()),
                ('v10', models.FloatField()),
                ('v11', models.FloatField()),
                ('v12', models.FloatField()),
                ('v13', models.FloatField()),
                ('v14', models.FloatField()),
                ('v15', models.FloatField()),
                ('v16', models.FloatField()),
                ('v17', models.FloatField()),
                ('v18', models.FloatField()),
                ('v19', models.FloatField()),
                ('v20', models.FloatField()),
                ('v21', models.FloatField()),
                ('v22', models.FloatField()),
                ('v23', models.FloatField()),
                ('v24', models.FloatField()),
                ('v25', models.FloatField()),
                ('v26', models.FloatField()),
                ('v27', models.FloatField()),
                ('v28', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('confidence', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
